services:
  db:
    image: postgres:16
    container_name: creditengine-db
    environment:
      POSTGRES_DB: creditengine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: creditengine-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/creditengine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: creditengine-front
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: